'use client';
import {useState} from 'react';
import {FileText,Copy,Download,ArrowUpRight,CheckCircle2} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {articleSeeds,modelName,COMPANY,SHOP,type Product} from '@/lib/storefront';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export default function ArticleStudio({products}:{products:Product[]}){
 const [title,setTitle]=useState(articleSeeds[0].title),[keyword,setKeyword]=useState('205/55R16'),[description,setDescription]=useState(articleSeeds[0].description),[body,setBody]=useState(articleSeeds[0].body),[sources,setSources]=useState(articleSeeds[0].source),[selected,setSelected]=useState<number[]>([4519,3638]),[notice,setNotice]=useState(''),[prompt,setPrompt]=useState('');
 const picked=products.filter(p=>selected.includes(p.id));
 const html=()=>`<!-- wp:heading --><h2>${esc(title)}</h2><!-- /wp:heading -->\n`+body.split(/\n\s*\n/).map(p=>`<!-- wp:paragraph --><p>${esc(p)}</p><!-- /wp:paragraph -->`).join('\n')+`\n<!-- wp:heading --><h2>สินค้าที่เกี่ยวข้อง</h2><!-- /wp:heading -->\n`+picked.map(p=>`<!-- wp:paragraph --><p><a href="${esc(p.url)}">${esc(p.brand+' '+modelName(p)+' '+p.size+' ปี '+p.year)}</a> — ตรวจราคาและสต็อกล่าสุดที่หน้าสินค้า</p><!-- /wp:paragraph -->`).join('\n')+(sources.trim()?`\n<!-- wp:paragraph --><p>แหล่งข้อมูล: ${esc(sources)}</p><!-- /wp:paragraph -->`:'');
 async function copy(value:string,label:string){try{await navigator.clipboard.writeText(value);setNotice(label+'แล้ว')}catch{setNotice('คัดลอกอัตโนมัติไม่ได้ กรุณาเลือกข้อความและคัดลอกเอง')}}
 function makePrompt(){const text=`เขียนร่างบทความภาษาไทยให้ร้าน ${SHOP} (${COMPANY})\nหัวข้อ: ${title}\nคำค้นหลัก: ${keyword}\nคำอธิบาย: ${description}\n\nข้อมูลสินค้าที่ตรวจสอบแล้ว ณ 7 ก.ย. 2026:\n${picked.map(p=>`ID ${p.id} | ${p.name} | URL ${p.url}`).join('\n')}\n\nแหล่งอ้างอิงที่ให้ตรวจอ่านก่อนเขียน:\n${sources||'ยังไม่ได้เพิ่มแหล่งอ้างอิง กรุณาขอข้อมูลก่อนสรุปข้อเท็จจริงทางเทคนิค'}\n\nข้อกำหนด: เปิดด้วยคำตอบสั้นที่ตรงคำถาม จากนั้นใช้ H2/H3 และคำถามที่ลูกค้าถามจริง ระบุผู้เขียน/ผู้ตรวจและวันที่เมื่อทราบ ห้ามแต่งราคา สต็อก รีวิว ผลทดสอบ ระยะเบรก อายุใช้งาน หรือขนาด OEM หากไม่พบข้อมูลให้ระบุจุดที่ต้องตรวจ ไม่ยัดคำค้น ไม่อ้างว่าเป็นตัวแทนจำหน่ายถ้าไม่มีหลักฐาน สินค้าแทรกเป็นลิงก์จากรายการข้างต้น ห้ามสรุปว่ายางขนาดเดียวกันเหมาะกับรถทุกคัน ส่งออก title, meta description, เนื้อหา, FAQ, sources และรายการที่ต้องให้เจ้าหน้าที่อนุมัติ นี่เป็น DRAFT ไม่ใช่การอนุมัติเผยแพร่`;setPrompt(text);setNotice('สร้างบรีฟแล้ว สามารถคัดลอกให้ AI ที่พี่ใช้อยู่ได้ ยังไม่ได้เรียกโมเดล AI จากเว็บ')}
 function download(){const file={status:'draft',title,excerpt:description,content:html(),seo:{title,description,keyword},sourceUrls:sources.split('\n').filter(Boolean),relatedProductIds:selected,reviewRequired:true,company:COMPANY};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(file,null,2)],{type:'application/json'}));a.download='lc-tyre-article-draft.json';a.click();URL.revokeObjectURL(a.href);setNotice('ดาวน์โหลดร่างแล้ว ยังไม่มีการส่งเข้า WordPress')}
 return <div className="studio"><div className="studio-intro"><FileText/><div><b>AI → ร่างบทความ → ผูกสินค้า → ตรวจและเผยแพร่</b><p>ทดลองเตรียมบทความและส่งออกสำหรับ WordPress · ยังไม่เชื่อม AI provider หรือหลังบ้านจริง</p></div></div><div className="studio-columns"><div><label className="form-field">หัวข้อ / SEO title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="form-field">คำค้นหลัก<input value={keyword} onChange={e=>setKeyword(e.target.value)}/></label><label className="form-field">Meta description<textarea rows={2} value={description} onChange={e=>setDescription(e.target.value)}/><small>{description.length} ตัวอักษร · ตรวจว่าคำอธิบายตรงเนื้อหา</small></label><label className="form-field">แหล่งข้อมูลสำหรับ AI (หนึ่ง URL ต่อบรรทัด)<textarea rows={2} value={sources} onChange={e=>setSources(e.target.value)} placeholder="https://…"/></label><button className="btn orange" onClick={makePrompt}>สร้างบรีฟให้ AI <ArrowUpRight size={16}/></button>{prompt&&<div className="prompt-output"><textarea aria-label="บรีฟสำหรับ AI" readOnly value={prompt} rows={8}/><button className="btn light" onClick={()=>copy(prompt,'คัดลอกบรีฟ')}>คัดลอกบรีฟ <Copy size={15}/></button></div>}</div><div><label className="form-field">วางร่างจาก AI แล้วแก้ไขได้เลย<textarea rows={12} value={body} onChange={e=>setBody(e.target.value)}/></label><fieldset className="product-picker"><legend>แทรกสินค้าจาก WooCommerce เดิม</legend>{products.filter(p=>['205/55R16','265/65R17'].includes(p.size)).slice(0,14).map(p=><label key={p.id}><Checkbox checked={selected.includes(p.id)} onCheckedChange={checked=>setSelected(s=>checked?[...s,p.id]:s.filter(id=>id!==p.id))}/><span>{p.brand} {modelName(p)}<small>{p.size} · ปี {p.year} · ID {p.id}</small></span></label>)}</fieldset></div></div><div className="seo-preview"><span>ตัวอย่างผลการค้นหา</span><small>lctyre.com › articles › …</small><b>{title}</b><p>{description}</p></div><div className="studio-actions"><button className="btn orange" onClick={()=>copy(html(),'คัดลอก Gutenberg HTML')}>คัดลอกเข้า WordPress <Copy size={16}/></button><button className="btn light" onClick={download}>ส่งออกร่าง JSON <Download size={16}/></button></div><p className="note">คัดลอก HTML ไปยัง Code editor ของโพสต์ WordPress แล้วบันทึกเป็นร่าง · ไม่ฝังราคาลงบทความเพื่อป้องกันราคาล้าสมัย</p><p className="notice" role="status">{notice&&<CheckCircle2 size={16}/>} {notice}</p></div>
}
